---
#- hosts: spark
#  roles:
#    - common
#    - spark
#    - shark
#
#- hosts: streaming
#  roles:
#    - common
#    - streaming

- hosts: [mllib-master, mllib-slave, mllib-gateway]
  roles:
    - common
    - mllib
