---
zookeeper_home: /opt/zookeeper-3.4.6
zookeeper_data: /data/zookeeper
zookeeper_classpath:
  - "{{ zookeeper_home }}/lib/slf4j-log4j12-1.6.1.jar"
  - "{{ zookeeper_home }}/lib/slf4j-api-1.6.1.jar"
  - "{{ zookeeper_home }}/lib/netty-3.7.0.Final.jar"
  - "{{ zookeeper_home }}/lib/log4j-1.2.16.jar"
  - "{{ zookeeper_home }}/lib/jline-0.9.94.jar"
  - "{{ zookeeper_home }}/zookeeper-3.4.6.jar"
  - "{{ zookeeper_home }}/conf"

kafka_home: /opt/kafka_2.10-0.8.1.1
kafka_log: /data/kafka
kafka_zkroot: /kafka
kafka_classpath:
  - "{{ kafka_home }}/libs/jopt-simple-3.2.jar"
  - "{{ kafka_home }}/libs/kafka_2.10-0.8.1.1-javadoc.jar"
  - "{{ kafka_home }}/libs/kafka_2.10-0.8.1.1-scaladoc.jar"
  - "{{ kafka_home }}/libs/kafka_2.10-0.8.1.1-sources.jar"
  - "{{ kafka_home }}/libs/kafka_2.10-0.8.1.1.jar"
  - "{{ kafka_home }}/libs/log4j-1.2.15.jar"
  - "{{ kafka_home }}/libs/metrics-core-2.2.0.jar"
  - "{{ kafka_home }}/libs/scala-library-2.10.1.jar"
  - "{{ kafka_home }}/libs/slf4j-api-1.7.2.jar"
  - "{{ kafka_home }}/libs/snappy-java-1.0.5.jar"
  - "{{ kafka_home }}/libs/zkclient-0.3.jar"
  - "{{ kafka_home }}/libs/zookeeper-3.3.4.jar"
  - "{{ kafka_home }}/config/log4j.properties"
