---
- name: install kafka
  unarchive: src=/opt/downloads/kafka_2.10-0.8.1.1.tgz dest=/opt/ creates={{ kafka_home }} copy=no

- name: config kafka
  template: src=server.properties.j2 dest={{ kafka_home }}/config/server.properties

- name: create kafka log dir
  file: path={{ kafka_log }} state=directory

- name: create kafka dirs
  file: path={{ item }} state=directory
  with_items: kafka_dirs

- name: config supervisor
  template: src=kafka.conf.j2 dest=/etc/supervisor/conf.d/kafka.conf
