---
- name: install zookeeper
  unarchive: src=/opt/downloads/zookeeper-3.4.6.tar.gz dest=/opt/ creates={{ zookeeper_home }} copy=no

- name: create zookeeper data directory
  file: path={{ zookeeper_data }} state=directory

- name: config zookeeper
  template: src=zookeeper-zoo.cfg.j2 dest={{ zookeeper_home }}/conf/zoo.cfg

- name: config myid
  template: src=zookeeper-myid.j2 dest={{ zookeeper_data }}/myid

- name: config supervisor
  template: src=zookeeper-supervisor.conf.j2 dest=/etc/supervisor/conf.d/zookeeper.conf
