---
- name: rsync /opt/downloads
  synchronize: src=/opt/downloads dest=/opt/

- name: install oracle jdk7
  unarchive: src=/opt/downloads/jdk-7u45-linux-x64.gz dest=/usr/lib/jvm/ creates={{ java_home }} copy=no

- name: install scala 2.10
  unarchive: src=/opt/downloads/scala-2.10.3.tgz dest=/opt/ creates={{ scala_home }} copy=no

- name: ssh public key
  authorized_key: user=root key="{{ item }}"
  with_file:
    - root.pub
